name: Test workflows
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
      - name: Prepare environment
        run: |
          conda create -n sonify -c conda-forge ffmpeg obspy
      - name: Install
        shell: bash -l {0}
        run: |
          conda activate sonify
          pip install -e .
      - name: Test CLI
        shell: bash -l {0}
        run: |
          conda activate sonify
          sonify --help
