name: Test workflows
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up conda
        run: conda init
      - name: Prepare environment
        run: |
          conda create -n sonify -c conda-forge ffmpeg obspy
          conda activate sonify
      - name: Install
        run: pip install -e .
      - name: Test CLI
        run: sonify --help
